(define-public %treesitter-packages
  '("tree-sitter"

    "tree-sitter-python"
    "tree-sitter-go"
    "tree-sitter-rust"
    "tree-sitter-c"
    "tree-sitter-cpp"
    "tree-sitter-javascript"
    "tree-sitter-typescript"
    "tree-sitter-json"
    "tree-sitter-yaml"
    "tree-sitter-bash"
    "tree-sitter-css"
    "tree-sitter-html"
    "tree-sitter-markdown"
    "tree-sitter-ocaml"
    "tree-sitter-scheme"
    "tree-sitter-elisp"
    "tree-sitter-dockerfile"
    "tree-sitter-toml"
    "tree-sitter-lua"
    "tree-sitter-nix"))
