[theme]
theme = "ctp-mocha"
[theme.overrides]
idle_bg = "#1d1f21"
idle_fg = "#c4c8c5"
info_bg = "#363a41"
info_fg = "#c4c8c5"
good_bg = "#1d1f21"
good_fg = "#c4c8c5"
warning_bg = "#f0c574"
warning_fg = "#1d1f21"
critical_bg = "#cc6666"
critical_fg = "#1e1e2e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome6"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = "$icon $zram_decompressed"
[[block]]
block = "load"
interval = 1

[[block]]
block = "cpu"

[[block]]
block = "temperature"
interval = 10
chip = "*-isa-*"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "

[[block]]
block = "net"
format = "  $speed_down  $speed_up "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "weather"
format = " $icon $temp "
[block.service]
name = "openweathermap"
api_key = "3e321f9414eaedbfab34983bda77a66e" # awesome lains default api_key
city_id = "113646" # Tabriz, Iran city_id
units = "metric"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%R') "

